logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.mycomp: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

#spring:
#  thymeleaf:
#    cache: false
#azure:
#  activedirectory:
#    client-id: 957543e2-580e-40e2-81f3-39f5c95a8f28
#    client-secret: ${AZURE_CLIENT_SECRET}
#    tenant-id: b705d325-1562-4111-a055-b0b7dd21c002
#    authorization-clients:
#      myservicesapp_appregistration_app:
#        scopes: openid, profile, offline_access
server:
  port: 8080

base-url: ${BASE_URL:http://localhost:8080}