logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.mycomp: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

#spring:
#  thymeleaf:
#    cache: false
azure:
  activedirectory:
    client-id: ${AZURE_CLIENT_ID}
    client-secret: ${AZURE_CLIENT_SECRET}
    tenant-id: ${AZURE_TENANT_ID}
    redirect-uri-template: https://myservicesab.azurewebsites.net/login/oauth2/code/
    authorization-clients:
      myservicesab2:
        scopes: openid, profile, offline_access, api://5001c70e-cf59-488c-a616-dfd32356a2de/user_impersonation

server:
  port: 8080

base-url: ${BASE_URL:http://localhost:8080}

#test@venkatabhumireddyyleminc.onmicrosoft.com/Ylem2022
#https://sts.windows.net/b705d325-1562-4111-a055-b0b7dd21c002/v2.0