logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.mycomp: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

#spring:
#  thymeleaf:
#    cache: false
azure:
  activedirectory:
    client-id: ${AZURE_CLIENT_ID}
    client-secret: ${AZURE_CLIENT_SECRET}
    tenant-id: ${AZURE_TENANT_ID}
    authorization-clients:
      myservicesapp_appregistration_app:
        scopes: openid, profile, offline_access

server:
  port: 8080

base-url: ${BASE_URL:http://localhost:8080}

#test@venkatabhumireddyyleminc.onmicrosoft.com/Ylem2022